Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -7,7 +7,7 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
-
+  
     steps:
     - uses: actions/checkout@v4
     - name: Set up JDK 21
@@ -20,6 +20,13 @@ jobs:
       run: mvn -B package --file pom.xml
     - name: Test
       run: mvn test
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v5
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/target/surefire-reports/TEST-*.xml'
+        detailed_summary: true
+        fail_on_failure: false
 
   security-check:
       needs: [build]
